services:
  # MongoDB database
  mongodb:
    image: mongo:7
    container_name: polls-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=polls
    networks:
      - polls-network

  # Backend API
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: polls-backend
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/polls
      - NODE_ENV=development
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - polls-network

  # Frontend Angular app
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: polls-frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - polls-network

volumes:
  mongo_data:

networks:
  polls-network:
    driver: bridge