services:
  # Backend API
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: polls-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    env_file:
      - ./backend/.env # to retrieve MONGODB_URI from .env file
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - polls-network

  # Frontend Angular app
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: polls-frontend
    ports:
      - "4200:4200" # for development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - polls-network

networks:
  polls-network:
    driver: bridge